Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: AWS::SSM::Parameter::Value<String>
    Default: /dev/ec2/instanceType
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
  ImageId: # Public SSM Paramater
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
  ServerSecurityGroup:
    Description: SecurityGroup for EC2
    Type: AWS::EC2::SecurityGroup::GroupName
    Default: launch-wizard-1

Resources:
  Test:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      AvailabilityZone: "ap-southeast-1"
      SecurityGroups:
        - !Ref ServerSecurityGroup
  EbsVolume:
    Type: AWS::EC2::Volume
    Properties:
      Volum

  
