Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: AWS::SSM::Parameter::Value<String>
    Default: /dev/ec2/instanceType
  InstanceRole:
    Description: Iam role for EC2
    Type: AWS::IAM::InstanceProfile::InstanceProfileName
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: Laptop
  ImageId:
    Description: Select latest AMI from Public SSM Paramater
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
  ServerSecurityGroup:
    Description: SecurityGroup for EC2
    Type: AWS::EC2::SecurityGroup::GroupName
    Default: jarvis-ec2

Resources:
  TestEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      AvailabilityZone: ap-southeast-1a
      SecurityGroups:
        - !Ref ServerSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            VolumeSize: 30
            DeleteOnTermination: true
            Encrypted: false

  # EbsVolume:
  #   Type: AWS::EC2::Volume
  #   Properties: 
  #     VolumeType: gp3
  #     Size: 30
  #     AvailabilityZone: !GetAtt TestEc2.AvailabilityZone
    

  
